name: 'Chart.yaml version verification'
description: 'Verify Chart.yaml version bump'
inputs:
  USER_TOKEN: 
    required: true
runs:
  using: "composite"
  steps:
    - id: diff
      run: | 
        files=$(git diff --diff-filter=ACDMR --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- 'charts/*' ':!*/Chart.yaml' | awk 'BEGIN{FS="/";OFS="/"};{print $1,$2,"Chart.yaml"}' | uniq)
        echo "files: $files"
        echo 'diff_files<<EOF' >> $GITHUB_ENV
        echo $files >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      shell: bash
    - run: |
        set +e
        for file in ${{ env.diff_files }}
          do
            git diff --diff-filter=M ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- $file | grep -E "^[-+]version:"
            (( $? )) && curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ inputs.USER_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments -d "{\"body\":\"Update \`version\` for $file\"}" && exit 1
          done 
          echo "All versions verified"
      if: env.diff_files
      shell: bash          
