name: CI3

on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/check-charts
        with:
          USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: event action
        run: echo ${{ github.event.action }} 
        shell: bash 
      - name: Pull R merged
        run: echo ${{ github.event.pull_request.merged }} 
        shell: bash 
      - run: echo "Merge false"
        shell: bash
        if: github.event.pull_request.merged == false
      - run: echo "Merge true"
        shell: bash
        if: github.event.pull_request.merged == true
