name: CI3

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/check-charts
        with:
          USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Nie działa na merge"
        shell: bash
        if: github.event.pull_request.merged == false
      - run: echo "DZiała na merge"
        shell: bash
        if: github.event.pull_request.merged == true
